### ISSUE TITLE
is it possible to estimate mutual information for two vectors? 

### ISSUE THREAD

**Issue by goodnamegood** [EEthinker/JVHW_Entropy_Estimators#2]
I've seen lots of similar repos saying that they estimate mutual information between two variables, but sometimes these variables are scalar variables. Could you provide examples in calculating the mutual information between two vector variables? Assume the number of data samples can be infinitely large.

**Comment by omnireasoner** [comment]
Hi @goodnamegood since we are now considering discrete random variables, the scalar and vector cases are not that different. For example, suppose the vector has two entries, each takes values in an alphabet of size M. Then, as a vector, we can map it to a scalar random variable that takes values in an alphabet of size M^2.
